(define (x00) 1)
(define (x01) 0)
(define (x02) 1)
(define (x03) 1)
(define (x04) 0)
(define (y00) 1)
(define (y01) 1)
(define (y02) 1)
(define (y03) 1)
(define (y04) 1)
(define (mjb) (logxor (ntg) (fgs)))
(define (tnw) (logor (y02) (x01)))
(define (z05) (logor (kwq) (kpj)))
(define (fst) (logor (x00) (x03)))
(define (z01) (logxor (tgd) (rvg)))
(define (bfw) (logor (vdt) (tnw)))
(define (z10) (logand (bfw) (frj)))
(define (bqk) (logor (ffh) (nrd)))
(define (djm) (logand (y00) (y03)))
(define (psh) (logor (y03) (y00)))
(define (z08) (logor (bqk) (frj)))
(define (frj) (logor (tnw) (fst)))
(define (z11) (logand (gnj) (tgd)))
(define (z00) (logxor (bfw) (mjb)))
(define (vdt) (logor (x03) (x00)))
(define (z02) (logand (gnj) (wpb)))
(define (kjc) (logand (x04) (y00)))
(define (qhw) (logor (djm) (pbm)))
(define (hwm) (logand (nrd) (vdt)))
(define (rvg) (logand (kjc) (fst)))
(define (fgs) (logor (y04) (y02)))
(define (pbm) (logand (y01) (x02)))
(define (kwq) (logor (ntg) (kjc)))
(define (tgd) (logxor (psh) (fgs)))
(define (z09) (logxor (qhw) (tgd)))
(define (kpj) (logor (pbm) (djm)))
(define (ffh) (logxor (x03) (y03)))
(define (ntg) (logxor (x00) (y04)))
(define (z06) (logor (bfw) (bqk)))
(define (wpb) (logxor (nrd) (fgs)))
(define (z04) (logxor (frj) (qhw)))
(define (z07) (logor (bqk) (frj)))
(define (nrd) (logor (y03) (x01)))
(define (z03) (logand (hwm) (bqk)))
(define (z12) (logxor (tgd) (rvg)))
(define (gnj) (logor (tnw) (pbm)))
(define (z) (+
  (ash (z00) 0)
  (ash (z01) 1)
  (ash (z02) 2)
  (ash (z03) 3)
  (ash (z04) 4)
  (ash (z05) 5)
  (ash (z06) 6)
  (ash (z07) 7)
  (ash (z08) 8)
  (ash (z09) 9)
  (ash (z10) 10)
  (ash (z11) 11)
  (ash (z12) 12)
))
(display (z)) (newline)
