export CHEZSCHEMELIBDIRS=../lib::.
SCHEME=/opt/chez/bin/scheme

debug:
	$(SCHEME) puz1.ss

test1:
	$(SCHEME) --program puz1.ss test.txt

puz1:
	$(SCHEME) --program puz1.ss input.txt

test2:
	$(SCHEME) --program puz2.ss test.txt

puz2:
	$(SCHEME) --program puz2.ss input.txt

debug2:
	$(SCHEME) puz2.ss
